from enum import StrEnum


class ClaimStandard(StrEnum):
    NPHIES = "NPHIES"
    ECLAIMLINK = "ECLAIMLINK"
    SHAFAFIYA = "SHAFAFIYA"
    CANONICAL = "CANONICAL"


class Jurisdiction(StrEnum):
    KSA = "KSA"
    DUBAI = "DUBAI"
    ABU_DHABI = "ABU_DHABI"
    UNKNOWN = "UNKNOWN"


class PayloadStatus(StrEnum):
    DRAFT_BUILDING = "DRAFT_BUILDING"
    DRAFT_BUILT = "DRAFT_BUILT"
    DRAFT_INVALID = "DRAFT_INVALID"
    VALIDATED = "VALIDATED"
    READY_TO_SUBMIT = "READY_TO_SUBMIT"
    SUBMITTED = "SUBMITTED"
    WAITING_FOR_PAYER = "WAITING_FOR_PAYER"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    NEEDS_PRIOR_AUTH = "NEEDS_PRIOR_AUTH"
    NEEDS_PAYLOAD_REBUILD = "NEEDS_PAYLOAD_REBUILD"
    HOLD_CRITICAL = "HOLD_CRITICAL"


class EligibilityStatus(StrEnum):
    CACHED_VALID = "CACHED_VALID"
    PASS = "PASS"
    FAIL_HOLD_CRITICAL = "FAIL_HOLD_CRITICAL"
    FAIL_OUT_OF_NETWORK = "FAIL_OUT_OF_NETWORK"
    WAITING_FOR_PAYER = "WAITING_FOR_PAYER"
    MANUAL_PORTAL_TASK = "MANUAL_PORTAL_TASK"


class PriorAuthStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    ALREADY_VALID = "ALREADY_VALID"
    APPROVED = "APPROVED"
    DENIED_NEEDS_REVIEW = "DENIED_NEEDS_REVIEW"
    WAITING_FOR_PAYER = "WAITING_FOR_PAYER"
    HOLD_CRITICAL = "HOLD_CRITICAL"
    REQUIRED_MISSING = "REQUIRED_MISSING"


class ValidationStatus(StrEnum):
    READY_TO_SUBMIT = "READY_TO_SUBMIT"
    NEEDS_PRIOR_AUTH = "NEEDS_PRIOR_AUTH"
    NEEDS_PAYLOAD_REBUILD = "NEEDS_PAYLOAD_REBUILD"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    HOLD_CRITICAL = "HOLD_CRITICAL"


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"


class CallbackSource(StrEnum):
    WEBHOOK = "WEBHOOK"
    POLL = "POLL"
    MANUAL = "MANUAL"


class ExternalTransactionStatus(StrEnum):
    CREATED = "CREATED"
    SENT = "SENT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    QUEUED = "QUEUED"
    PENDED = "PENDED"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
