export const demoClaims = [
  {
    id: "CLM-DXB-2001",
    patient: "Mariam Al Ketbi",
    mrn: "DXB-889321",
    payer: "Oman Insurance",
    payerId: "INS-OMAN-DXB",
    plan: "Premium Network",
    jurisdiction: "Dubai",
    standard: "eClaimLink",
    serviceDate: "2026-06-15",
    updated: "8m ago",
    status: "needs_review",
    score: 78,
    amount: "AED 650.00",
    builtClaim: {
      payloadType: "xml",
      objectUri: "claims/CLM-DXB-2001/payloads/eclaimlink.xml",
      hash: "7b95d91f3e6a",
      generatedAt: "2026-06-15 14:32",
      schemaStatus: "xsd_warning",
      payload:
        '<Claim.Submission>\n  <Header>\n    <SenderID>DHA-FAC-001</SenderID>\n    <ReceiverID>INS-OMAN-DXB</ReceiverID>\n    <TransactionDate>15/06/2026 14:32</TransactionDate>\n  </Header>\n  <Claim>\n    <ID>CLM-DXB-2001</ID>\n    <MemberID>M-77821</MemberID>\n    <PayerID>INS-OMAN-DXB</PayerID>\n    <ProviderID>DHA-FAC-001</ProviderID>\n    <Encounter>\n      <Start>15/06/2026 10:00</Start>\n      <End>15/06/2026 10:25</End>\n    </Encounter>\n    <Diagnosis>\n      <Type>Principal</Type>\n      <Code>J18.9</Code>\n    </Diagnosis>\n    <Activity>\n      <Type>3</Type>\n      <Code>99213</Code>\n      <Net>650.00</Net>\n    </Activity>\n  </Claim>\n</Claim.Submission>',
    },
    route: {
      claimStandard: "ECLAIMLINK",
      priorAuthStandard: "ECLAIMLINK",
      eligibilityStandard: "ECLAIMLINK",
      payerPortal: "DHA eClaimLink",
      confidence: 0.96,
    },
    validation: {
      summary: { critical: 1, warnings: 2, info: 1 },
      checks: [
        { name: "Metadata Consistency", status: "pass", issues: [] },
        {
          name: "Payload Conformity",
          status: "warn",
          issues: [
            {
              severity: "warning",
              code: "ECLAIMLINK_ATTACHMENT_REFERENCE",
              field: "claim.attachments[0]",
              message: "Attachment metadata is present, but upload reference is not attached to the XML payload.",
              fix: "Upload the radiology report and store the portal attachment reference.",
            },
          ],
        },
        { name: "Financial Consistency", status: "pass", issues: [] },
        { name: "Eligibility", status: "pass", issues: [] },
        {
          name: "Prior Authorization",
          status: "fail",
          issues: [
            {
              severity: "critical",
              code: "PA_REQUIRED_MISSING",
              field: "prior_auth",
              message: "Payer rules require prior authorization for the selected procedure.",
              fix: "Run the prior authorization module before submission.",
            },
          ],
        },
        {
          name: "Coding Consistency",
          status: "warn",
          issues: [
            {
              severity: "warning",
              code: "DOCUMENTATION_SUPPORT_THIN",
              field: "clinical_context.soap_note",
              message: "SOAP note supports the visit, but medical necessity narrative is short.",
              fix: "Add clinical details from radiology and assessment.",
            },
          ],
        },
      ],
    },
    eligibility: {
      status: "eligible",
      checkedAt: "2026-06-15 14:20",
      reference: "ELG-DXB-78121",
      method: "portal_response",
      notes: "Coverage active for date of service.",
    },
    priorAuth: {
      status: "required_missing",
      requiredCodes: ["99213"],
      preAuthRef: null,
      requestStatus: "not_started",
      nextStep: "Build and submit eClaimLink PA request.",
    },
    audit: [
      { at: "14:02", node: "fhir_context", status: "completed", detail: "Encounter, patient, coverage, provider, documents loaded." },
      { at: "14:11", node: "router", status: "completed", detail: "Dubai route selected: eClaimLink." },
      { at: "14:32", node: "claim_builder", status: "completed", detail: "eClaimLink XML generated." },
      { at: "14:36", node: "validation", status: "needs_review", detail: "Prior authorization required before submission." },
    ],
  },
  {
    id: "CLM-AUH-10482",
    patient: "Ahmed Al Mansouri",
    mrn: "AUH-092112",
    payer: "Daman",
    payerId: "DAMAN_AE",
    plan: "Thiqa Gold",
    jurisdiction: "Abu Dhabi",
    standard: "Shafafiya",
    serviceDate: "2026-06-18",
    updated: "12m ago",
    status: "waiting",
    score: 88,
    amount: "AED 1,375.00",
    builtClaim: {
      payloadType: "xml",
      objectUri: "claims/CLM-AUH-10482/payloads/shafafiya.xml",
      hash: "8f2a1c9e4b7d",
      generatedAt: "2026-06-18 14:32",
      schemaStatus: "valid",
      payload:
        '<Claim.Submission>\n  <Header>\n    <SenderID>MF2057</SenderID>\n    <ReceiverID>A001</ReceiverID>\n    <TransactionDate>18/06/2026 14:32</TransactionDate>\n  </Header>\n  <Claim>\n    <ID>CLM-AUH-10482</ID>\n    <MemberID>THIQA-44210</MemberID>\n    <EmiratesIDNumber>784-1990-1111111-8</EmiratesIDNumber>\n    <PayerID>A001</PayerID>\n    <ProviderID>MF2057</ProviderID>\n    <Diagnosis>\n      <Type>Principal</Type>\n      <Code>K04.0</Code>\n    </Diagnosis>\n    <Activity>\n      <Type>3</Type>\n      <Code>D3330</Code>\n      <Clinician>GD-44211</Clinician>\n      <Gross>1375.00</Gross>\n      <Net>1375.00</Net>\n    </Activity>\n  </Claim>\n</Claim.Submission>',
    },
    route: {
      claimStandard: "SHAFAFIYA",
      priorAuthStandard: "SHAFAFIYA",
      eligibilityStandard: "SHAFAFIYA",
      payerPortal: "DOH Shafafiya",
      confidence: 0.98,
    },
    validation: {
      summary: { critical: 0, warnings: 2, info: 1 },
      checks: [
        { name: "Metadata Consistency", status: "pass", issues: [] },
        { name: "Payload Conformity", status: "pass", issues: [] },
        { name: "Eligibility", status: "pass", issues: [] },
        {
          name: "Prior Authorization",
          status: "waiting",
          issues: [
            {
              severity: "info",
              code: "PA_PAYER_QUEUE",
              field: "prior_auth.request",
              message: "Prior authorization was accepted by portal and is waiting for payer response.",
              fix: "Polling worker should continue until complete, denied, or escalated.",
            },
          ],
        },
        {
          name: "Documentation",
          status: "warn",
          issues: [
            {
              severity: "warning",
              code: "RADIOLOGY_ATTACHMENT_PENDING",
              field: "documents.radiology",
              message: "Radiology image is referenced but the final portal attachment ID is not stored.",
              fix: "Attach final portal reference after upload.",
            },
          ],
        },
      ],
    },
    eligibility: {
      status: "eligible",
      checkedAt: "2026-06-18 14:03",
      reference: "VOI-DAMAN-55017",
      method: "VOI",
      notes: "Daman VOI active. Plan requires PA for endodontic therapy.",
    },
    priorAuth: {
      status: "queued",
      requiredCodes: ["D3330"],
      preAuthRef: null,
      requestStatus: "waiting_for_payer",
      nextStep: "Continue polling payer callback queue.",
    },
    audit: [
      { at: "14:00", node: "fhir_context", status: "completed", detail: "FHIR resources loaded." },
      { at: "14:01", node: "router", status: "completed", detail: "Abu Dhabi route selected: Shafafiya." },
      { at: "14:12", node: "prior_auth_graph", status: "waiting", detail: "PA request queued by payer." },
      { at: "14:32", node: "claim_builder", status: "completed", detail: "Shafafiya XML built and stored." },
    ],
  },
  {
    id: "CLM-KSA-77812",
    patient: "Fahad Al Harbi",
    mrn: "KSA-512880",
    payer: "Tawuniya",
    payerId: "TAWUNIYA",
    plan: "Corporate Class A",
    jurisdiction: "KSA",
    standard: "NPHIES",
    serviceDate: "2026-06-20",
    updated: "2h ago",
    status: "ready",
    score: 96,
    amount: "SAR 450.00",
    builtClaim: {
      payloadType: "fhir_bundle",
      objectUri: "claims/CLM-KSA-77812/payloads/nphies.json",
      hash: "d7c21ba81a92",
      generatedAt: "2026-06-20 11:14",
      schemaStatus: "nphies_sandbox_ready",
      payload:
        '{\n  "resourceType": "Bundle",\n  "type": "message",\n  "meta": {\n    "profile": ["http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/bundle|1.0.0"]\n  },\n  "entry": [\n    { "resource": { "resourceType": "MessageHeader", "eventCoding": { "code": "claim-request" } } },\n    { "resource": { "resourceType": "Claim", "id": "CLM-KSA-77812", "use": "claim" } }\n  ]\n}',
    },
    route: {
      claimStandard: "NPHIES",
      priorAuthStandard: "NPHIES",
      eligibilityStandard: "NPHIES",
      payerPortal: "NPHIES HSB",
      confidence: 0.99,
    },
    validation: {
      summary: { critical: 0, warnings: 0, info: 1 },
      checks: [
        { name: "Metadata Consistency", status: "pass", issues: [] },
        { name: "Payload Conformity", status: "pass", issues: [] },
        { name: "Financial Consistency", status: "pass", issues: [] },
        { name: "Eligibility", status: "pass", issues: [] },
        { name: "Prior Authorization", status: "pass", issues: [] },
        { name: "Submission Readiness", status: "pass", issues: [] },
      ],
    },
    eligibility: {
      status: "eligible",
      checkedAt: "2026-06-20 10:54",
      reference: "ELG-NPHIES-9110",
      method: "nphies_bundle_response",
      notes: "CoverageEligibilityResponse outcome complete.",
    },
    priorAuth: {
      status: "not_required",
      requiredCodes: [],
      preAuthRef: null,
      requestStatus: "not_required",
      nextStep: "Ready for submission.",
    },
    audit: [
      { at: "10:50", node: "fhir_context", status: "completed", detail: "Clinical and coverage resources loaded." },
      { at: "10:51", node: "router", status: "completed", detail: "KSA route selected: NPHIES." },
      { at: "11:10", node: "validation", status: "ready", detail: "All blocking checks passed." },
    ],
  },
  {
    id: "CLM-AUH-10501",
    patient: "Salma Al Nuaimi",
    mrn: "AUH-902712",
    payer: "Daman",
    payerId: "DAMAN_AE",
    plan: "Basic",
    jurisdiction: "Abu Dhabi",
    standard: "Shafafiya",
    serviceDate: "2026-06-11",
    updated: "1d ago",
    status: "hold",
    score: 43,
    amount: "AED 4,200.00",
    builtClaim: {
      payloadType: "xml",
      objectUri: "claims/CLM-AUH-10501/payloads/shafafiya.xml",
      hash: "05ae60dce927",
      generatedAt: "2026-06-11 09:48",
      schemaStatus: "valid",
      payload:
        '<Claim.Submission>\n  <Header>\n    <SenderID>MF2057</SenderID>\n    <ReceiverID>A001</ReceiverID>\n    <TransactionDate>11/06/2026 09:48</TransactionDate>\n  </Header>\n  <Claim>\n    <ID>CLM-AUH-10501</ID>\n    <PayerID>A001</PayerID>\n    <ProviderID>MF2057</ProviderID>\n    <Diagnosis>\n      <Type>Principal</Type>\n      <Code>M17.11</Code>\n    </Diagnosis>\n    <Activity>\n      <Type>3</Type>\n      <Code>27447</Code>\n      <Net>4200.00</Net>\n    </Activity>\n  </Claim>\n</Claim.Submission>',
    },
    route: {
      claimStandard: "SHAFAFIYA",
      priorAuthStandard: "SHAFAFIYA",
      eligibilityStandard: "SHAFAFIYA",
      payerPortal: "DOH Shafafiya",
      confidence: 0.98,
    },
    validation: {
      summary: { critical: 3, warnings: 1, info: 0 },
      checks: [
        {
          name: "Eligibility",
          status: "fail",
          issues: [
            {
              severity: "critical",
              code: "COVERAGE_OUTSIDE_SERVICE_DATE",
              field: "coverage.period",
              message: "Coverage period does not include the date of service.",
              fix: "Fetch updated coverage or hold submission.",
            },
          ],
        },
        {
          name: "Prior Authorization",
          status: "fail",
          issues: [
            {
              severity: "critical",
              code: "PA_EXPIRED",
              field: "prior_auth.valid_to",
              message: "Prior authorization expired before the service date.",
              fix: "Request a new authorization and rebuild the claim with the new reference.",
            },
          ],
        },
        {
          name: "Documentation",
          status: "fail",
          issues: [
            {
              severity: "critical",
              code: "MISSING_RADIOLOGY",
              field: "documents.radiology",
              message: "Radiology evidence is required for this procedure.",
              fix: "Attach radiology report before submission.",
            },
          ],
        },
      ],
    },
    eligibility: {
      status: "not_eligible",
      checkedAt: "2026-06-11 09:10",
      reference: "VOI-DAMAN-55120",
      method: "VOI",
      notes: "Coverage inactive for date of service.",
    },
    priorAuth: {
      status: "expired",
      requiredCodes: ["27447"],
      preAuthRef: "PA-DAMAN-OLD-0911",
      requestStatus: "expired",
      nextStep: "New PA request required.",
    },
    audit: [
      { at: "09:03", node: "fhir_context", status: "completed", detail: "Source context loaded." },
      { at: "09:05", node: "eligibility_graph", status: "failed", detail: "Eligibility check returned inactive coverage." },
      { at: "09:08", node: "prior_auth_graph", status: "failed", detail: "Existing PA is expired." },
      { at: "09:48", node: "validation", status: "hold", detail: "Critical blockers remain." },
    ],
  },
];
